### ISSUE TITLE
Updates post-bootcamp

### ISSUE THREAD

**Issue by matboivin** [42-AI/bootcamp_python#109]
## Global notes:

- [x] Global English checking and rephrasing

### day00/ex01
- [x] Change output example or add explanations #94

### day01/ex04
- [x] 1. Add latex examples for additions between scalar and vectors #85
- [x] 2. Vector multiplication is not the same as Dot Product #103

### day01/ex04
- [ ] Create a better subject for the generator #86
